language: python
python:
- '3.6'
env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
branches:
  only:
  - master
install:
- pip install --upgrade awscli
- export PATH=$PATH:$HOME/.local/bin
script: ./bin/test.sh && ./bin/upload.sh
notifications:
  slack:
    rooms:
      - civicsoftware:NWEsYkoW7oJjtQ65WZNgL5Rr#buildnotifications